name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          cache: True
      - name: Build Tests
        run: |
          mkdir build-test
          cd build-test
          qmake ../test/
          make clean
          make -j32
          strip test
        shell: bash
      - name: Run Tests
        run: |
          cd build-test
          ./test
        shell: bash
